# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-25 16:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import property.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=property.models.get_image_filename, verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('prop_desc', models.TextField()),
                ('location_desc', models.TextField()),
                ('draft', models.BooleanField(default=False)),
                ('publish', models.DateField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('furnished', models.NullBooleanField()),
                ('roomnumber', models.IntegerField()),
                ('buildingage', models.IntegerField()),
                ('metrekare', models.IntegerField()),
                ('price', models.FloatField()),
                ('floornumber', models.IntegerField()),
                ('heating_choice', models.CharField(choices=[('Do', 'Dogalgaz'), ('So', 'Soba'), ('El', 'Elektrik')], default='Do', max_length=4)),
                ('sale_choice', models.CharField(choices=[('Re', 'Rent'), ('Sa', 'Sale')], default='Re', max_length=4)),
                ('prop_choice', models.CharField(choices=[('Rs', 'Residance'), ('Wp', 'Workplace'), ('Bu', 'Building'), ('Ld', 'Land')], default='Rs', max_length=4)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
        migrations.CreateModel(
            name='UserProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ufurnished', models.NullBooleanField()),
                ('furwchoice', models.IntegerField(blank=True, null=True)),
                ('uroomnumber', models.IntegerField(blank=True, null=True)),
                ('ubuildingage', models.IntegerField(blank=True, null=True)),
                ('roomwchoice', models.IntegerField(blank=True, null=True)),
                ('umetrekaremin', models.IntegerField(blank=True, null=True)),
                ('mminwchoice', models.IntegerField(blank=True, null=True)),
                ('umetrekaremax', models.IntegerField(blank=True, null=True)),
                ('mmaxwchoice', models.IntegerField(blank=True, null=True)),
                ('upricemin', models.FloatField(blank=True, null=True)),
                ('pminwchoice', models.IntegerField(blank=True, null=True)),
                ('upricemax', models.FloatField(blank=True, null=True)),
                ('pmaxwchoice', models.IntegerField(blank=True, null=True)),
                ('ufloornumber', models.IntegerField(blank=True, null=True)),
                ('floorwchoice', models.IntegerField(blank=True, null=True)),
                ('uheating_choice', models.CharField(choices=[('Do', 'Dogalgaz'), ('So', 'Soba'), ('El', 'Elektrik')], default='Do', max_length=4)),
                ('usale_choice', models.CharField(choices=[('Re', 'Rent'), ('Sa', 'Sale')], default='Re', max_length=4)),
                ('uprop_choice', models.CharField(choices=[('Rs', 'Residance'), ('Wp', 'Workplace'), ('Bu', 'Building'), ('Ld', 'Land')], default='Rs', max_length=4)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='like',
            name='prop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Property'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='images',
            name='prop1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Property'),
        ),
    ]
